/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exam_jni_Order_Stu */

#ifndef _Included_com_exam_jni_Order_Stu
#define _Included_com_exam_jni_Order_Stu
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
