/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exam_jni_Order */

#ifndef _Included_com_exam_jni_Order
#define _Included_com_exam_jni_Order
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exam_jni_Order
 * Method:    sort
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_exam_jni_Order_sort
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_exam_jni_Order
 * Method:    sortInts
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_exam_jni_Order_sortInts
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_exam_jni_Order
 * Method:    sortStr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_exam_jni_Order_sortStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_exam_jni_Order
 * Method:    sortStu
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_exam_jni_Order_sortStu
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
