/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exam_slieer_utils_jni_HelloNextNative */

#ifndef _Included_com_exam_slieer_utils_jni_HelloNextNative
#define _Included_com_exam_slieer_utils_jni_HelloNextNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exam_slieer_utils_jni_HelloNextNative
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_exam_slieer_utils_jni_HelloNextNative_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_exam_slieer_utils_jni_HelloNextNative
 * Method:    setInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_exam_slieer_utils_jni_HelloNextNative_setInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
