/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exam_slieer_utils_jni_HelloJavaBeanNative */

#ifndef _Included_com_exam_slieer_utils_jni_HelloJavaBeanNative
#define _Included_com_exam_slieer_utils_jni_HelloJavaBeanNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exam_slieer_utils_jni_HelloJavaBeanNative
 * Method:    setUser
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_exam_slieer_utils_jni_HelloJavaBeanNative_setUser
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_exam_slieer_utils_jni_HelloJavaBeanNative
 * Method:    getUser
 * Signature: ()Lcom/exam/slieer/utils/bean/User;
 */
JNIEXPORT jobject JNICALL Java_com_exam_slieer_utils_jni_HelloJavaBeanNative_getUser
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
