/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exam_slieer_utils_jni_HelloNative */

#ifndef _Included_com_exam_slieer_utils_jni_HelloNative
#define _Included_com_exam_slieer_utils_jni_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exam_slieer_utils_jni_HelloNative
 * Method:    callCppFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exam_slieer_utils_jni_HelloNative_callCppFunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
