/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exam_slieer_utils_jni_corejava8jni_Printf2 */

#ifndef _Included_com_exam_slieer_utils_jni_corejava8jni_Printf2
#define _Included_com_exam_slieer_utils_jni_corejava8jni_Printf2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exam_slieer_utils_jni_corejava8jni_Printf2
 * Method:    sprint
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_exam_slieer_utils_jni_corejava8jni_Printf2_sprint
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     com_exam_slieer_utils_jni_corejava8jni_Printf2
 * Method:    fprint
 * Signature: (Ljava/io/PrintWriter;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_exam_slieer_utils_jni_corejava8jni_Printf2_fprint
  (JNIEnv *, jclass, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
